### ISSUE TITLE
[Bug] The authentication error that occurs only when the 16KB page size is enabled

### ISSUE THREAD

**Issue by genta-mz** [firebase/firebase-unity-sdk#1277]
### Description

Regarding the crash caused by the 16KB page size issue reported [here](https://github.com/firebase/firebase-unity-sdk/issues/1259), we have confirmed that the issue has been resolved in Firebase Unity SDK version `12.10.0`. However, we have encountered the following problem, which we would like to bring to your attention for further investigation.

When launching the app with a 16KB page size on a device that is **not logged into a Google account**, the following error occurs during Firebase initialization:

```
06-30 17:22:47.863 E/FirebaseInstanceId(13632): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
06-30 17:22:47.916 E/Unity   (13632): FirebaseException: AUTHENTICATION_FAILED
```

Logging into a Google account on the device resolves the issue, and even after deleting the account from the device, the problem does not recur. However, if the device is reset and the app is launched again with no Google account logged in, the original error reappears. This suggests some issue related to devices that are not logged into a Google account.

**Note:** This problem does not occur on Android devices that are not set to a 16KB page size, nor does it occur on iOS devices.

Additionally, though the connection here is unclear, the error log references `FirebaseInstanceId`. It appears that the latest version of `com.google.firebase.instance-id` is `7.2.0`, released in May 2021, but this library has since been deprecated:

- [Firebase Instance ID Privacy Overview](https://firebase.google.com/support/privacy/manage-iids?hl=en)
- [Firebase Instance ID Documentation](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId)

In our implementation, we do not explicitly specify the `com.google.firebase.instance-id` library. This raises the concern that something unexpected might be happening inside the Firebase SDK's internal mechanisms. We wanted to highlight this as a potential cause and provide this information for further review.

### Reproducing the issue

- Initialize the device and set it to a state where the Google account is logged out.
- Enable the 16KB page size.
- Execute FirebaseMessaging.GetTokenAsync() from an application that integrates Firebase SDK version 12.10.0.
- An AUTHENTICATION_FAILED error occurs.

### Firebase Unity SDK Version

12.10.0

### Unity editor version

2022.3.58f1

### Installation Method

Unity Package Manager

### Problematic Firebase Component(s)

Authentication

### Targeted Platform(s)

Android

### Unity editor platform

Mac

### Scripting Runtime

IL2CPP

### Release Distribution Type

Pre-built SDK from https://firebase.google.com/download/unity

### Relevant Log Output

```shell
06-30 17:22:40.738 I/firebase(13632): Firebase Analytics API Initializing
06-30 17:22:40.739 I/firebase(13632): analytics API Initialized
06-30 17:22:40.741 I/firebase(13632): Firebase Cloud Messaging API Initialized
06-30 17:22:40.753 I/Unity   (13632): [***.Log]resolve all Firebase dependencies: Available
06-30 17:22:40.753 I/Unity   (13632): <size=10><i>InitializeAsync() at FirebaseService.cs:172</i></size>

06-30 17:22:40.762 D/BackgroundInstallControlService( 1343): Package event received: 0
06-30 17:22:40.762 I/firebase(13632): Firebase Analytics API Initializing
06-30 17:22:40.762 I/firebase(13632): analytics API Initialized
06-30 17:22:40.763 I/firebase(13632): Firebase Cloud Messaging API Initialized

06-30 17:22:40.779 E/FirebaseInstanceId(13632): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.

06-30 17:22:40.812 I/Unity   (13632): Firebase Analytics API Initializing
06-30 17:22:40.812 I/Unity   (13632): Firebase.AppUtilPINVOKE:PollCallbacks()
06-30 17:22:40.812 I/Unity   (13632): Firebase.AppUtil:PollCallbacks()
06-30 17:22:40.812 I/Unity   (13632): Firebase.Platform.FirebaseHandler:Update()
06-30 17:22:40.812 I/Unity   (13632): 
06-30 17:22:40.813 I/Unity   (13632): analytics API Initialized
06-30 17:22:40.813 I/Unity   (13632): Firebase.AppUtilPINVOKE:PollCallbacks()
06-30 17:22:40.813 I/Unity   (13632): Firebase.AppUtil:PollCallbacks()
06-30 17:22:40.813 I/Unity   (13632): Firebase.Platform.FirebaseHandler:Update()
06-30 17:22:40.813 I/Unity   (13632): 
06-30 17:22:40.814 I/Unity   (13632): Firebase Cloud Messaging API Initialized
06-30 17:22:40.814 I/Unity   (13632): Firebase.AppUtilPINVOKE:PollCallbacks()
06-30 17:22:40.814 I/Unity   (13632): Firebase.AppUtil:PollCallbacks()
06-30 17:22:40.814 I/Unity   (13632): Firebase.Platform.FirebaseHandler:Update()
06-30 17:22:40.814 I/Unity   (13632): 

06-30 17:22:47.833 I/Unity   (13632): [***.Log]resolve all Firebase dependencies: Available
06-30 17:22:47.833 I/Unity   (13632): <size=10><i>InitializeAsync() at FirebaseService.cs:172</i></size>

06-30 17:22:47.863 E/FirebaseInstanceId(13632): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
```

### If using CocoaPods for Apple platforms, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

👀 Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by argzdev** [comment]
Hey @genta-mz, thanks for filing a well detailed report. I'm trying to reproduce the issue according to your steps, however somehow I'm not encountering this issue using our [Firebase Unity quickstart for messaging](https://github.com/firebase/firebase-unity-sdk/tree/main/messaging). Here's the steps I did to test the scenario:

1. Create new virtual emulator API version 36 with "Pre-release 16 KB Page Size Google Play ARM 64 v8a System Image"
2. Run `adb shell getconf PAGE_SIZE` to see if output is `16384` to verify that it's using a 16 KB environment
4. Open Firebase Unity quickstart for messaging](https://github.com/firebase/firebase-unity-sdk/tree/main/messaging)
5. Add `FirebaseMessaging.unitypackage` version `12.10.0` (I also tried adding `FirebaseAuth.unitypackage`)
6. Call `Firebase.Messaging.FirebaseMessaging.GetTokenAsync()`
7. Successful retrieval of the token

```
2025/07/03 00:12:16.078 4334 4426 Info Unity GetTokenAsync completed
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Sample.Messaging.UIHandler:DebugLog(String)
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Sample.Messaging.UIHandler:LogTaskCompletion(Task, String)
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Sample.Messaging.<>c__DisplayClass21_0:<GUIDisplayControls>b__3(Task`1)
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1()
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0()
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.ExceptionAggregator:Wrap(Action)
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Dispatcher:PollJobs()
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Platform.FirebaseHandler:Update()
2025/07/03 00:12:16.078 4334 4426 Info Unity 
2025/07/03 00:12:16.078 4334 4426 Info Unity GetTokenAsync result: eMHYNNejQtycokdHMYMosS:APA91bGvE3J4uzSk7qKBbDSZwNicnU3Em-D1LTQYpcN5Z9fXhBPJ_YbW1gJLZQ3TsxWePhpA9Mf7Khn1WuwY-ejJ4hx181ZsZQLJEUXL50MmCWPtKN1UvhI
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Sample.Messaging.UIHandler:DebugLog(String)
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1()
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0()
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.ExceptionAggregator:Wrap(Action)
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Dispatcher:PollJobs()
2025/07/03 00:12:16.078 4334 4426 Info Unity Firebase.Platform.FirebaseHandler:Update()
```

Since the virtual emulator is newly created, no google play account has been logged in yet. I also checked to make sure no accounts has been added. However, so far the issue is not reproducible. Not sure if there's any steps that I'm missing.

**Comment by argzdev** [comment]
Hi @genta-mz, that's an odd behavior. Firebase Messaging should work without any dependency from other Firebase products. In fact, I thought you needed to add FirebaseAuth to reproduce the behavior. So I'm not quite sure what is triggering the issue. It could be something else entirely.

Upon checking the native [Firebase Android SDK for Firebase Messaging](https://github.com/firebase/firebase-android-sdk/blob/5959a5026859dd27ad2bedb28d94ada75097de5b/firebase-messaging/src/main/java/com/google/firebase/iid/FirebaseInstanceIdReceiver.java#L38). It does seem like the FCM is still using Firebase Instance ID within its codebase, though it still doesn't give any clue what's causing the behavior.

That said, could you try removing FirebaseAuth, and see if still works? If it does, then it could've been a server problem causing a temporary issue.

**Comment by genta-mz** [comment]
Thank you for confirming.

The error reported in this issue occurred while FirebaseAuth was not implemented.
Since @argzdev's reproduction steps included "adding FirebaseAuth," I tried doing the same, and the error was resolved.

It is possible that FirebaseMessaging may not function correctly with a 16KB page size unless FirebaseAuth is integrated.
Would it be possible to perform another round of reproduction verification with FirebaseAuth excluded to confirm this hypothesis?

**Comment by argzdev** [comment]
Hi @genta-mz, sure I did try to test the scenario again using our Firebase quickstart for Firebase Messaging without FirebaseAuth, so far the issue is still not reproducible. I'm wondering, is this an issue you're only able to reproduce on a physical device or are you also encountering this issue on an android emulator? If you like us to investigate further, could you provide an [MCVE](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean), so we can take a closer look into it.

**Comment by genta-mz** [comment]
@argzdev 
We've resolved our immediate issue by adding FirebaseAuth, so we'll close this for now. (Apologies for not being able to prepare a Minimal, Complete, and Verifiable Example.) If new problems arise, we'll reach out again. Thanks so much for all your help!
