### ISSUE TITLE
[Bug] Apple Silicon - DllNotFoundException

### ISSUE THREAD

**Issue by tab1887** [firebase/firebase-unity-sdk#278]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.2.0b4 Apple Silicon
  * Firebase Unity SDK version: 8.1.0
  * Source you installed the SDK: .unitypackage 
  * Problematic Firebase Component: Auth and others
  * Other Firebase Components in use: None
  * Additional SDKs you are using: None
  * Platform you are using the Unity editor on: Mac / MacBook Air M1
  * Platform you are targeting: iOS (Any)
  * Scripting Runtime: Mono (Any)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

After importing the FirebaseAuth package into an empty Unity project with the Apple Silicon Version of the Unity Editor and initializing the the module with a simple

FirebaseAuth auth = FirebaseAuth.DefaultInstance;

I get the following Exception when entering play mode:

DllNotFoundException: FirebaseCppApp-8_1_0 assembly:<unknown assembly> type:<unknown type> member:(null)
Firebase.AppUtilPINVOKE+SWIGExceptionHelper..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:117)
Rethrow as TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
Firebase.AppUtilPINVOKE..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/AppUtilPINVOKE.cs:137)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.AppUtilPINVOKE' threw an exception.
Firebase.AppUtil.SetLogFunction (Firebase.LogUtil+LogMessageDelegate arg0) (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/AppUtil.cs:64)
Firebase.LogUtil..ctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/LogUtil.cs:81)
Firebase.LogUtil..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/LogUtil.cs:37)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.LogUtil' threw an exception.
Firebase.FirebaseApp..cctor () (at Z:/tmp/tmp.9PHv6s9T8D/firebase/app/client/unity/proxy/FirebaseApp.cs:67)
Rethrow as TypeInitializationException: The type initializer for 'Firebase.FirebaseApp' threw an exception.
Firebase.Auth.FirebaseAuth.get_DefaultInstance () (at Z:/tmp/tmp.fXb0dO0rk8/firebase/auth/client/unity/proxy/FirebaseAuth.cs:295)
FirebaseAuthTest.Start () (at Assets/FirebaseAuthTest.cs:11)

When doing the same in the Intel version of the Unity beta then a popup appears about an untrusted developer for FirebaseCppApp-8_1_0.bundle, which can be worked around by allowing execution through the MacOs system security settings. But in the Apple Silicon version this popup does never appear.

**Comment by steffen-roemer** [comment]
A dirty workaround that works for me with 8.10.0 is to use the FirebaseCppApp-8_8_0.bundle from the bundles @samskivert  provided above, rename it to FirebaseCppApp-8_10_0.bundle and call /usr/bin/xattr -d com.apple.quarantine path/to/project/Assets/Firebase/Plugins/x86_64/FirebaseCppAuth.bundle on it

**Comment by nodrock** [comment]
I created repo with actual modified .tgz files supporting Apple silicon for Firebase SDK 8.10.1. Feel free to use it and hopefully Google will start to provide it as soon as possible in official releases. It is ridiculous why it took them so long. If there will be any problems let me know pls. 

https://github.com/nodrock/firebase_sdk_silicon

**Comment by vincentkrp** [comment]
@steffen-roemer Thx for the tip. I did the exact same thing but for some kind of reason it just doesn't work for me. I'm still getting the DllNotFoundException.

**Comment by DhirenJakhariya** [comment]
> OK, updated 8.8.0 bundles are here: https://samskivert.com/firebase-bundles.zip

Hi @samskivert 
Please can you update bundle in firebase 8.9.0 version ?
it's huge for us.

**Comment by samskivert** [comment]
Hi all,

I built the latest bits for 8.10.1, which are at the same URL: https://samskivert.com/firebase-bundles.zip

I have only tested Firebase Core, Auth and Messaging as those are the packages we use, but everything else is built and included in the .zip file.

As mentioned, hopefully this will be the last release for which we need our own custom .bundle files.

**Comment by alex-blastproofgames** [comment]
@samskivert Thanks for the bundles!

I don't have any idea how to use them though. Any help would be appreciated.

**Comment by georgemarkosian** [comment]
> 

1. Import Firebase libs into your project using unity packages
2. Go to Assets/Firebase/Plugins folder and create arm64 folder
3. Copy all arm64 bundles into that folder just as it's in x86_64
4. Then you need to configure bundle files to be used on macs with apple silicon CPU. It's done in Unity Editor

**Comment by alex-blastproofgames** [comment]
Thank you!

**Comment by a-maurice** [comment]
Hi all,

We've released a new version of the Firebase for Unity SDK, 9.0.0, available here: https://github.com/firebase/firebase-unity-sdk/releases/tag/v9.0.0, which adds support for Apple Silicon chips.

Sorry it took a while to add this support, and thanks to all the folks who provided workarounds in the meantime.

**Comment by Thaina** [comment]
I still got `DllNotFoundException: FirebaseCppApp-9_0_0`

Not sure it related to this issue. But I use latest unity 2022.1

**Comment by kadaxo** [comment]
`DllNotFoundException: FirebaseCppApp-9_1_0`  still have the problem
