### ISSUE TITLE
[Bug] FBLPromises(FBLPromise.o)' does not contain bitcode OR FirebaseAnalytics(FIRAnalytics.o)' does not contain bitcode

### ISSUE THREAD

**Issue by dcosmin-97** [firebase/firebase-unity-sdk#556]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.42f1
  * Google Mobile Ads Unity plugin version: 7.3.1
  * Platform: iOS
  * Mediation ad networks used, and their versions: AdColony 2.6.0, Applovin 6.4.3, Meta 3.9.0, Pangle 1.3.1, Vungle 3.9.0
  * Firebase 10.1.1
  

### [REQUIRED] Step 2: Describe the problem

When I want to build in Xcode 14.1, I get the following errors:
/Build/Products/ReleaseForRunning-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises(FBLPromise.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target
/Build/Products/ReleaseForRunning-iphoneos/PromisesObjC/FBLPromises.framework/FBLPromises' for architecture arm64

In pods I have everything with Enable Bitcode = NO

I have tried to follow the tutorial from here: https://stackoverflow.com/questions/72904371/fblpromises-framework-does-not-contain-bitcode-failing-build but it doesn't work.

When I set Enable Bitcode to YES, I get the following errors:
/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics(FIRAnalytics.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file 
/Build/Products/ReleaseForRunning-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport/FirebaseAnalytics.framework/FirebaseAnalytics' for architecture arm64

I cannot download Xcode 13.x because of macOS Ventura

Has anyone found a solution?
Thank you!

![image](https://user-images.githubusercontent.com/66071707/204870432-e58fb8f0-5e4e-4726-ae43-704f00f37bd3.png)

**Comment by paulinon** [comment]
Hi @dcosmin-97,

Thanks for reporting this. [Version 10.2.0](https://firebase.google.com/support/release-notes/unity#version_1020_-_november_30_2022) of the Firebase SDK has been released recently. Could you try this out and see if it makes a difference? Also, does the issue persist with just the Firebase SDK in your implementation? 

It's quite odd that you're facing a similar error message after enabling bitcode. It's possible that updating your other SDKs may resolve the issue.

**Comment by GoatHunter** [comment]
@paulinon hi, we're having the same exact issue with `Firebase 10.2.0` , I've enabled bitcode in all the generated Pods by inject this into the Podfile:
```ruby
post_install do |installer|
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['ENABLE_BITCODE'] = 'YES'
  end
 end
end
```

Xcode Version 14.0.1 (14A400), macOS Monterey 12.6 (21G115).

Please assist with resolving this issue, we can't build for iOS.

**Comment by GoatHunter** [comment]
Update: 

Resolved, seems that Apple have deprecated Bitcode beginning with Xcode 14 hence libraries began disabling bitcode in their builds:

```
Deprecations
Starting with Xcode 14, bitcode is no longer required for watchOS and tvOS applications, and the App Store no longer 
accepts bitcode submissions from Xcode 14.

Xcode no longer builds bitcode by default and generates a warning message if a project explicitly enables bitcode: 
"Building with bitcode is deprecated. Please update your project and/or target settings to disable bitcode." The capability 
to build with bitcode will be removed in a future Xcode release. IPAs that contain bitcode will have the bitcode stripped 
before being submitted to the App Store. Debug symbols can only be downloaded from App Store Connect / TestFlight for 
existing bitcode submissions and are no longer available for submissions made with Xcode 14. (86118779)
```

Source: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

To resolve this I did two things -
1. Force disabled Bitcode in the main Unity generated project, the tests and the framework.
2. Force disable Bitcode in Pods.

Here's a snippet of our build post processing script - 
** Note that the Cocoapods method (`RemoveCocoapodsIPhoneOsDeploymentTarget`) also disables CODE_SIGNING_ALLOWED and sets the deployment target to the one configured in Unity, you may want to remove those or keep those, they're not strictly related to the issue, but it helped us to get our project compiling with Xcode 14.

```C#
#if UNITY_IOS
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using System.IO;
using UnityEditor.Build.Reporting;

public class PostBuild {
    
    [PostProcessBuild(45)]
    private static void RemoveCocoapodsIPhoneOsDeploymentTarget(BuildTarget buildTarget, string pathToBuiltProject)
    {
        if (buildTarget == BuildTarget.iOS)
        {
            // https://stackoverflow.com/a/51416359
            var content = "\n\npost_install do |installer|\n" +
                                   "installer.pods_project.targets.each do |target|\n" +
                                   "  target.build_configurations.each do |config|\n" +
                                  $"    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '{PlayerSettings.iOS.targetOSVersionString}'\n" +
                                   // https://stackoverflow.com/questions/72561696/xcode-14-needs-selected-development-team-for-pod-bundles
                                   $"    config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'\n" +
                                   "    config.build_settings['ENABLE_BITCODE'] = 'NO'\n" +
                                   "  end\n" +
                                  " end\n" +
                                  "end\n";

            using var streamWriter = File.AppendText(Path.Combine(pathToBuiltProject, "Podfile"));
            streamWriter.WriteLine(content);
        }
    }


    [PostProcessBuild] static void OnPostProcessBuildDisableBitCode(BuildTarget buildTarget, string pathToBuiltProject)
    {
        string projPath = pathToBuiltProject + "/Unity-iPhone.xcodeproj/project.pbxproj";

        var pbxProject = new PBXProject();
        pbxProject.ReadFromFile(projPath);
        
        // Main
        string target = pbxProject.GetUnityMainTargetGuid();
        pbxProject.SetBuildProperty(target, "ENABLE_BITCODE", "NO");


        // Unity Tests
        target = pbxProject.TargetGuidByName(PBXProject.GetUnityTestTargetName());
        pbxProject.SetBuildProperty(target, "ENABLE_BITCODE", "NO");


        // Unity Framework
        target = pbxProject.GetUnityFrameworkTargetGuid();
        pbxProject.SetBuildProperty(target, "ENABLE_BITCODE", "NO");


        pbxProject.WriteToFile(projPath);
    }
}

#endif
```

**Comment by josealvarez97** [comment]
The issue persists with version 10.3 of the Firebase SDK and Xcode version 14.

**Comment by josealvarez97** [comment]
The following didn't work for me:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/21250471/212162956-772783c8-0fa5-4989-86d9-fcdf419f0da1.png">

What worked for me was setting the following flag to NO in all of these files.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/21250471/212163178-c9cbbee1-5616-47b3-9ef4-fc7221689498.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/21250471/212163076-0ab162ca-eb02-49b3-8a4f-9ca12b2799e6.png">

I am wondering if the approach followed here would have accomplished the same result: https://support.unity.com/hc/en-us/articles/207942813-How-can-I-disable-Bitcode-support-

For reference:
https://gist.github.com/guneyozsan/2f503015268e04748e0283da562b448c
https://developer.apple.com/forums/thread/714681

**Comment by josealvarez97** [comment]
> The following didn't work for me:
> 
> <img alt="image" width="762" src="https://user-images.githubusercontent.com/21250471/212162956-772783c8-0fa5-4989-86d9-fcdf419f0da1.png">
> 
> What worked for me was setting the following flag to NO in all of these files.
> 
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/21250471/212163178-c9cbbee1-5616-47b3-9ef4-fc7221689498.png">
> 
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/21250471/212163076-0ab162ca-eb02-49b3-8a4f-9ca12b2799e6.png">
> 
> I am wondering if the approach followed here would have accomplished the same result: https://support.unity.com/hc/en-us/articles/207942813-How-can-I-disable-Bitcode-support-
> 
> For reference: https://gist.github.com/guneyozsan/2f503015268e04748e0283da562b448c https://developer.apple.com/forums/thread/714681


^^ 

Yes, the code from [this article](https://support.unity.com/hc/en-us/articles/207942813-How-can-I-disable-Bitcode-support-) works like a charm.
