### ISSUE TITLE
[Bug] Crash on Android after adding AppCheck with Play Integrity

### ISSUE THREAD

**Issue by OleksiiSB** [firebase/firebase-unity-sdk#877]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2021.3.31f1
  * Firebase Unity SDK version: 11.2.0
  * Source you installed the SDK: unitypackage
  * Problematic Firebase Component: AppCheck
  * Other Firebase Components in use: Auth, Firestore, Installations, Analytics, Crashlytics, Remote Config, Functions, Storage
  * Additional SDKs you are using: Facebook, Applovin, AppsFlyer
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: Pre-built SDK

### [REQUIRED] Please describe the issue here:

After adding initialisation of the AppCheck we see random crashes from random set of devices that have AppCheck mentioned in the crash reports. We also have App Attest on iOS and it does not have similar problem. Sadly I was not able to repro this on the set of test devices we have and have only crash reports available to look into.

Reported from all versions of Android and all manufacturers. Distribution is similar to what we have in general distribution for all installs, so I don't believe this is somehow dependent on Android version or manufacturer.

Report 1:
```
pid: 0, tid: 11207 >>> APP_PACKAGE_NAME <<<

backtrace:
  #00  pc 0x00000000000531f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x00000000001a1d78  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libFirebaseCppApp-11_2_0.so (std::__ndk1::__throw_bad_function_call()+8)
  #02  pc 0x00000000001f6d40  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libFirebaseCppApp-11_2_0.so (firebase::app_check::FinishGetTokenCallback(int, char const*, long, int, char const*)+740)
  #03  pc 0x0000000001f2589c  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (AppCheckUtilPINVOKE_FinishGetTokenCallback_mFB5FBA27638D576459A05BEDE234A736213FF5B0) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #04  pc 0x0000000001f2349c  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (AppCheckUtil_FinishGetTokenCallback_m7634A953D905DD5F9C10AC0C6F8C96D3A8594176) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #05  pc 0x0000000001f239e4  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (U3CU3Ec__DisplayClass21_0_U3CGetTokenFromCSharpMethodU3Eb__0_mE3048D66FB5433928EE8CAD29997AD26E783BEBF) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #06  pc 0x0000000001d0cfa4  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (Task_Execute_m4FBCBCE932B924AD239A2448AED5708B6D14A7F1) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #07  pc 0x0000000001d62b9c  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (ExecutionContext_RunInternal_mC37E85D6FC972DF219A00FE1EE34329D1D63CC94) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #08  pc 0x0000000001d0d390  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (Task_ExecuteWithThreadLocal_mD3F4E7ADBBC473EAF7C24B3A785EBB452D6A76BE) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #09  pc 0x0000000001d0d24c  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (Task_ExecuteEntry_m735BD89474854D6EAA2ED929D6765AF1B4AEDCDF) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #10  pc 0x0000000001d672a0  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (ThreadPoolWorkQueue_Dispatch_mEAAC936B3756DAA856BA3A4D976A98A3184CDC87) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #11  pc 0x0000000000bafa7c  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (RuntimeInvoker_FalseByte_t94D9231AC217BE4D2E004C4CD32DF6D099EA41A3(void (*)(), MethodInfo const*, void*, void**, void*)) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #12  pc 0x0000000000c1ccd0  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**)) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #13  pc 0x0000000000c7bf14  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (worker_thread(void*)) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #14  pc 0x0000000000c872e0  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (il2cpp::vm::ThreadStart(void*)) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #15  pc 0x0000000000c7b18c  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (il2cpp::os::Thread::RunWrapper(void*)) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #16  pc 0x0000000000c97868  /data/app/~~45RRHydksFPFtcQ5greBVg==/APP_PACKAGE_NAME-WuYMtZraGyNtCggizTso8w==/lib/arm64/libil2cpp.so (il2cpp::os::ThreadImpl::ThreadStartWrapper(void*)) (BuildId: 8bbd7366f5af7b7d86aeb28cdbdfa9912c908e5e)
  #17  pc 0x00000000000c226c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204)
  #18  pc 0x0000000000054a30  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

Report 2:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 31571 >>> APP_PACKAGE_NAME <<<

backtrace:
  #00  pc 0x00000000001940f4  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/lib/arm64/libFirebaseCppApp-11_2_0.so (void std::__ndk1::__tree_balance_after_insert<std::__ndk1::__tree_node_base<void*>*>(std::__ndk1::__tree_node_base<void*>*, std::__ndk1::__tree_node_base<void*>*)+104)
  #01  pc 0x00000000001f82b0  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/lib/arm64/libFirebaseCppApp-11_2_0.so (firebase::app_check::SwigAppCheckProvider::GetToken(std::__ndk1::function<void (firebase::app_check::AppCheckToken, int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)>)+420)
  #02  pc 0x00000000002477d4  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/lib/arm64/libFirebaseCppApp-11_2_0.so (firebase::app_check::internal::JniAppCheckProvider_nativeGetToken(_JNIEnv*, _jobject*, long, _jobject*)+124)
  #03  pc 0x0000000000377030  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+144)
  #04  pc 0x000000000058b310  /apex/com.android.art/lib64/libart.so (nterp_helper+5648)
  #05  pc 0x0000000000000622  /data/user/0/APP_PACKAGE_NAME/cache/app_check_resources_lib.jar (com.google.firebase.appcheck.internal.cpp.JniAppCheckProvider.getToken+14)
  #06  pc 0x000000000058ba74  /apex/com.android.art/lib64/libart.so (nterp_helper+7540)
  #07  pc 0x0000000000de4a28  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/oat/arm64/base.vdex (com.google.firebase.appcheck.internal.DefaultFirebaseAppCheck.fetchTokenFromProvider+4)
  #08  pc 0x000000000058ac54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #09  pc 0x0000000000de4cce  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/oat/arm64/base.vdex (com.google.firebase.appcheck.internal.DefaultFirebaseAppCheck.lambda$getToken$2$com-google-firebase-appcheck-internal-DefaultFirebaseAppCheck+78)
  #10  pc 0x000000000058ac54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #11  pc 0x0000000001cc9824  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/oat/arm64/base.vdex (com.google.firebase.appcheck.internal.DefaultFirebaseAppCheck$$ExternalSyntheticLambda4.then+8)
  #12  pc 0x000000000215a460  /memfd:jit-cache (com.google.android.gms.tasks.zze.run+160)
  #13  pc 0x000000000056e33c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+796)
  #14  pc 0x000000000056b460  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
  #15  pc 0x000000000058bad4  /apex/com.android.art/lib64/libart.so (nterp_helper+7636)
  #16  pc 0x0000000000de9094  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/oat/arm64/base.vdex (com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory+24)
  #17  pc 0x000000000058ac54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924)
  #18  pc 0x000000000064e590  /data/app/~~wH08cFdfxq6V_kXGeFr9rw==/APP_PACKAGE_NAME-tO0ONpn_r1edS5QCnDUygg==/oat/arm64/base.vdex (com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run+8)
  #19  pc 0x0000000000419e08  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Thread.run+72)
  #20  pc 0x00000000003605a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #21  pc 0x000000000034b930  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #22  pc 0x00000000004f3e38  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1888)
  #23  pc 0x00000000000f5298  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #24  pc 0x000000000008ebdc  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
```

**Comment by paulinon** [comment]
Hi @OleksiiSB,

In order to ensure that your app has the latest updates and bug fixes, could you try if the latest SDK version ([11.5.0](https://firebase.google.com/support/release-notes/unity#version_1150_-_september_21_2023) as of writing) makes a difference?

**Comment by OleksiiSB** [comment]
We have updated SDK to the latest version for the new update that will start rollout Wednesday or Thursday. I will monitor crashes and update here as soon as we have info.

**Comment by OleksiiSB** [comment]
We didn't get to the public rollout to confirm that issue is still present after updating to latest 11.5.0 SDK. Report came from the closed beta user, so I can confirm updating does not resolve the issue. I also didn't find any mentions of changes related to the AppCheck in release notes of Unity SDK or Android SDK updates that were included between 11.2.0 and 11.5.0 Unity SDK versions.

**Comment by rubenwe** [comment]
We are also hitting the exact same issue in production right now. In our case we are on 11.4.0:

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 19852 >>> <bundle_id> <<<

backtrace:
  #00  pc 0x00000000000526f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #01  pc 0x00000000001a3e7c  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libFirebaseCppApp-11_4_0.so (std::__ndk1::__throw_bad_function_call()+8)
  #02  pc 0x00000000001f7e44  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libFirebaseCppApp-11_4_0.so (firebase::app_check::FinishGetTokenCallback(int, char const*, long, int, char const*)+740)
  #03  pc 0x000000000135bf58  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (AppCheckUtilPINVOKE_FinishGetTokenCallback_mFB5FBA27638D576459A05BEDE234A736213FF5B0+11759) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #04  pc 0x0000000001353bc0  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (AppCheckUtil_FinishGetTokenCallback_m7634A953D905DD5F9C10AC0C6F8C96D3A8594176+13488) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #05  pc 0x00000000013541bc  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (U3CU3Ec__DisplayClass21_0_U3CGetTokenFromCSharpMethodU3Eb__0_mE3048D66FB5433928EE8CAD29997AD26E783BEBF+4047) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #06  pc 0x000000000264d0d8  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (Task_Execute_m4FBCBCE932B924AD239A2448AED5708B6D14A7F1+29) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #07  pc 0x000000000263d5d4  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (ExecutionContext_RunInternal_mC37E85D6FC972DF219A00FE1EE34329D1D63CC94+31684) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #08  pc 0x000000000264d4b0  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (Task_ExecuteWithThreadLocal_mD3F4E7ADBBC473EAF7C24B3A785EBB452D6A76BE+25890) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #09  pc 0x000000000264d380  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (Task_ExecuteEntry_m735BD89474854D6EAA2ED929D6765AF1B4AEDCDF+22468) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #10  pc 0x0000000002642c28  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (ThreadPoolWorkQueue_Dispatch_mEAAC936B3756DAA856BA3A4D976A98A3184CDC87+161) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #11  pc 0x0000000000d62e74  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (RuntimeInvoker_FalseByte_t94D9231AC217BE4D2E004C4CD32DF6D099EA41A3(void (*)(), MethodInfo const*, void*, void**, void*)+146023) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #12  pc 0x0000000000e54690  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**)+588) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #13  pc 0x0000000000e41504  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (worker_thread(void*)+250) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #14  pc 0x0000000000e3a5d8  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (il2cpp::vm::ThreadStart(void*)+697) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #15  pc 0x0000000000e9380c  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (il2cpp::os::Thread::RunWrapper(void*)+201) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #16  pc 0x0000000000e0138c  /data/app/~~db4r4zYgNB3YxI_KOLer5g==/<bundle_id>-N_l0TE7qy021OEDLosPlvw==/lib/arm64/libil2cpp.so (il2cpp::os::ThreadImpl::ThreadStartWrapper(void*)+125) (BuildId: 8d5f6d4d9f893429d11469f9102da7872e560036)
  #17  pc 0x00000000000ba598  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #18  pc 0x0000000000053f3c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
  ```

**Comment by a-maurice** [comment]
Thanks for the callstacks everyone, I have tracked down what is likely the root cause of the problem, and we will aim to get a fix in for the next release.

**Comment by OleksiiSB** [comment]
Thanks for an update, we will update to the new SDK version when it is released and do small rollout of the build with it to see if it resolves the issue. I will update here in case it does not solve the issue.

**Comment by a-maurice** [comment]
We've released a new version, [11.6.0](https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.6.0), which contains the fix.  Hopefully this will solve the problems you all were seeing.  Thanks for bringing this to our attention.

**Comment by OleksiiSB** [comment]
We've rolled out update with a 11.6.0 Firebase SDK version to our players and the issue is still there.

```
pid: 0, tid: 9330 >>> BUNDLE_NAME <<<

backtrace:
  #00  pc 0x00000000000526f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168)
  #01  pc 0x00000000001a7504  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libFirebaseCppApp-11_6_0.so (std::__ndk1::__throw_bad_function_call()+8)
  #02  pc 0x00000000001fb450  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libFirebaseCppApp-11_6_0.so (firebase::app_check::FinishGetTokenCallback(int, char const*, long, int, char const*)+740)
  #03  pc 0x0000000001f60dcc  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (AppCheckUtilPINVOKE_FinishGetTokenCallback_mFB5FBA27638D576459A05BEDE234A736213FF5B0) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #04  pc 0x0000000001f5e9cc  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (AppCheckUtil_FinishGetTokenCallback_m7634A953D905DD5F9C10AC0C6F8C96D3A8594176) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #05  pc 0x0000000001f5ef14  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (U3CU3Ec__DisplayClass21_0_U3CGetTokenFromCSharpMethodU3Eb__0_mE3048D66FB5433928EE8CAD29997AD26E783BEBF) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #06  pc 0x0000000001d40500  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (Task_Execute_m4FBCBCE932B924AD239A2448AED5708B6D14A7F1) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #07  pc 0x0000000001d970f8  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (ExecutionContext_RunInternal_mC37E85D6FC972DF219A00FE1EE34329D1D63CC94) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #08  pc 0x0000000001d408ec  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (Task_ExecuteWithThreadLocal_mD3F4E7ADBBC473EAF7C24B3A785EBB452D6A76BE) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #09  pc 0x0000000001d407a8  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (Task_ExecuteEntry_m735BD89474854D6EAA2ED929D6765AF1B4AEDCDF) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #10  pc 0x0000000001d9b7fc  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (ThreadPoolWorkQueue_Dispatch_mEAAC936B3756DAA856BA3A4D976A98A3184CDC87) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #11  pc 0x0000000000bc47c8  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (RuntimeInvoker_FalseByte_t94D9231AC217BE4D2E004C4CD32DF6D099EA41A3(void (*)(), MethodInfo const*, void*, void**, void*)) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #12  pc 0x0000000000c2fe0c  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**)) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #13  pc 0x0000000000c90050  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (worker_thread(void*)) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #14  pc 0x0000000000c9b41c  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (il2cpp::vm::ThreadStart(void*)) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #15  pc 0x0000000000c8f2c8  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (il2cpp::os::Thread::RunWrapper(void*)) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #16  pc 0x0000000000cab9a4  /data/app/~~DthwDOwSaOhyUA6NrFKFtw==/BUNDLE_NAME-ACcjO8-Hech0DtCTewHzBg==/lib/arm64/libil2cpp.so (il2cpp::os::ThreadImpl::ThreadStartWrapper(void*)) (BuildId: 42cd4ff71758c6a136e08d08ca1d038e25366178)
  #17  pc 0x00000000000ba598  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #18  pc 0x0000000000053f3c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
```

**Comment by OleksiiSB** [comment]
@a-maurice tagging you for visibility

**Comment by a-maurice** [comment]
Drats, thanks for flagging this, and for the callstack.

**Comment by OleksiiSB** [comment]
Any updates on this issue?

**Comment by a-maurice** [comment]
Unfortunately we haven't been able to track down what the problem is, but we are still trying to track it down.

**Comment by Harsh-Xsquads** [comment]
Is there any updates on this issue?

**Comment by OleksiiSB** [comment]
@a-maurice any updates on this issue?

**Comment by OleksiiSB** [comment]
@a-maurice are there any updates on the issue?

**Comment by OleksiiSB** [comment]
@dconeybe @a-maurice any updates on when the next update of SDK will be released and if we will have a fix for this issue there?

**Comment by a-maurice** [comment]
Sorry for the delays, there were a lot of backend and dependency changes that caused problems with dependency updates.  We have resolved most of them now, and the next release with those updates should be early next week.  Unfortunately, for this specific issue, it is very hard for us to reproduce in our tests, so I can't say for certain if the next release will fix it or not.

**Comment by OleksiiSB** [comment]
We've had a rollout with Unity SDK 11.7.0 and the issue is not fully resolved (although it happens on relatively lower amount of sessions). Also as before there is no correlation on OS version or device.

![image](https://github.com/firebase/firebase-unity-sdk/assets/77016109/acda1df4-33fb-452e-897a-68074b482a34)

![image](https://github.com/firebase/firebase-unity-sdk/assets/77016109/96c7ffe1-8cc2-4b49-976e-b470ebecc553)

**Comment by a-maurice** [comment]
So, still wasn't able to reproduce the problem, but looking over the code and the error logs, I think that PR should help.  It'll be part of the next release, which should be out soon.

**Comment by OleksiiSB** [comment]
Thanks for the update! We will update to a next SDK release when it becomes available and try activating AppCheck again for the version of the application we have with it included.

**Comment by a-maurice** [comment]
Alright, the latest release has that fix, https://github.com/firebase/firebase-unity-sdk/releases/tag/v11.9.0

Hopefully that resolves the issue.  I'll close this for now, but if you are still seeing it, feel free to reopen it.
