### ISSUE TITLE
[Bug] Remote config fetch seems to hang forever on iOS on random sessions

### ISSUE THREAD

**Issue by BrooklynDipi** [firebase/firebase-unity-sdk#920]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2022.3.11f1
  * Firebase Unity SDK version: 11.6.0
  * Source you installed the SDK: tgz via UnityPackageManager
  * Problematic Firebase Component: RemoteConfig
  * Other Firebase Components in use: Auth, Crashlytics, Analytics, and External Dependency Manager
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows 11, MacOS
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP
  * Pre-built SDK from the [website](https://firebase.google.com/download/unity) or open-source from this repo: [Google APIs for Unity Archive](https://developers.google.com/unity/archive)

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

When using RemoteConfig on iOS devices, the function, FetchAsync(), has a roughly 30% chance of failing. This also occurs with FetchAndActivateAsync(). I use this tool to version check the application on start-up. If the application is out of date, it stops the user from progressing. Sometimes this function does not complete so the values needed to evaluate your continuation are not accurate. This issue does not occur on Android. 

I found a similar issue to this that occurred back in 2022 [here on the quickstart bug page](https://github.com/firebase/quickstart-unity/issues/1198#issuecomment-1040690857). They seemed to have solved it by setting the External Dependency Manager's iOS resolver settings to "Link Frameworks Statically" in addition to an SDK update. I suspect this is the issue that is possibly occurring for me currently. That said, I am unable to set "Link Frameworks Statically" to true as it breaks FacebookSDK.

The reason I suspect this is a similar issue is because of the logs I receive in XCode when running on iOS. I have debug logs that print the fetched version number as well as the current application version number. In this 30% chance window, I see the call stack for FetchAsync() begin but it does not produce any results, and the string that is set by its fetched values always results in an empty string.

I am hoping though that perhaps I am making a silly mistake and that this is not the reason. I have tried many different approaches to using the RemoteConfig API that have all resulted in a lack of consistency on iOS only. Android has been functional every time. I generally initialize Firebase in Awake() in our Auth script and I have previously hooked in the FetchAsync() function to that script, where its called after CheckAndFixDependenciesAsync(). No difference was made. 

I made sure to review and try approaches from the documentation [here.](https://firebase.google.com/docs/remote-config/get-started?platform=unity)

#### Steps to reproduce:

What's the issue repro rate? (eg 100%, 1/5 etc)

* Seems to be roughly 30%. I have tested this by simply closing and reopening the app on an iOS device to see if I get the intended results.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

* Fetch values from remote config with "Link Frameworks Statically" set to false.

#### Relevant Code:

```
using DG.Tweening;
using Firebase;
using Firebase.Extensions;
using Firebase.RemoteConfig;
using System;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;

public class RemoteConfigVersionControl : MonoBehaviour
{
    public static RemoteConfigVersionControl Instance;

    public GameObject UpdateGraphic;

    [HideInInspector]
    public bool isVersionCurrent = false;

    [HideInInspector]
    public string thisVersionNumber;

    [HideInInspector]
    public string currentVersionNumbers;

    private void Awake()
    {
        Instance = this;

        thisVersionNumber = Application.version;

        currentVersionNumbers = "0";
    }

    private async void Start()
    {
        await FirebaseApp.CheckAndFixDependenciesAsync();

        await FetchDataAsync();
    }

    private Task FetchDataAsync()
    {
        Debug.Log("Fetching data...");

        Task fetchTask = FirebaseRemoteConfig.DefaultInstance.FetchAsync(TimeSpan.Zero);

        return fetchTask.ContinueWithOnMainThread(FetchComplete);
    }

    private void FetchComplete(Task fetchTask)
    {
        if (!fetchTask.IsCompleted)
        {
            Debug.LogError("Retrieval hasn't finished.");
            return;
        }

        var remoteConfig = FirebaseRemoteConfig.DefaultInstance;

        var info = remoteConfig.Info;

        if (info.LastFetchStatus != LastFetchStatus.Success)
        {
            Debug.LogError($"{nameof(FetchComplete)} was unsuccessful\n{nameof(info.LastFetchStatus)}: {info.LastFetchStatus}");
            return;
        }

        // Fetch successful. Parameter values must be activated to use.
        remoteConfig.ActivateAsync()
          .ContinueWithOnMainThread(
            task =>
            {
                Debug.Log($"Remote data loaded and ready for use. Last fetch time {info.FetchTime}.");

                currentVersionNumbers = FirebaseRemoteConfig.DefaultInstance.GetValue("VersionNumber").StringValue;

                VersionComparison();
            });
    }

    public void VersionComparison()
    {
        Debug.Log("THIS VERSION NUMBER: " + thisVersionNumber);

        Debug.Log("CURRENT VERSION NUMBER: " + currentVersionNumbers);

        if (currentVersionNumbers == "0")
        {
            isVersionCurrent = true;
        }
        else if (currentVersionNumbers.Contains(thisVersionNumber))
        {
            isVersionCurrent = true;
        }
        else
        {
            isVersionCurrent = false;
        }
    }

    public void EnableUpdateGraphic()
    {
        if (UpdateGraphic != null)
        {
            var UpdateGraphicImage = UpdateGraphic.GetComponent<Image>();

            UpdateGraphic.SetActive(true);

            UpdateGraphicImage.DOFade(1, .5f);
        }
    }
}

```

Call stack for unfinished function
```
Fetching data...
RemoteConfigVersionControl:FetchDataAsync()
<Start>d__6:MoveNext()
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(TStateMachine&)
RemoteConfigVersionControl:Start()
```
Call stack for finished function
```
Fetching data...
RemoteConfigVersionControl:FetchDataAsync()
<Start>d__6:MoveNext()
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Runtime.CompilerServices.MoveNextRunner:Run()
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()

Remote data loaded and ready for use. Last fetch time 1/3/2024 9:03:55 PM.
<>c__DisplayClass8_0:<FetchComplete>b__0(Task`1)
Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1()
Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0()
Firebase.ExceptionAggregator:Wrap(Action)
Firebase.Dispatcher:PollJobs()
Firebase.Platform.FirebaseHandler:Update()

THIS VERSION NUMBER: 1.03.408
RemoteConfigVersionControl:VersionComparison()
<>c__DisplayClass8_0:<FetchComplete>b__0(Task`1)
Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1()
Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0()
Firebase.ExceptionAggregator:Wrap(Action)
Firebase.Dispatcher:PollJobs()
Firebase.Platform.FirebaseHandler:Update()

CURRENT VERSION NUMBER: 1.03.395
1.03.406

RemoteConfigVersionControl:VersionComparison()
<>c__DisplayClass8_0:<FetchComplete>b__0(Task`1)
Firebase.Extensions.<>c__DisplayClass4_1`1:<ContinueWithOnMainThread>b__1()
Firebase.<>c__DisplayClass5_0`1:<RunAsync>b__0()
Firebase.ExceptionAggregator:Wrap(Action)
Firebase.Dispatcher:PollJobs()
Firebase.Platform.FirebaseHandler:Update()
```

![image](https://github.com/firebase/firebase-unity-sdk/assets/44684333/08db6c93-5eea-4098-8ad8-614b1c6c78d6)

**Comment by georgemarkosian** [comment]
Hello there, we experience this one as well. We have several users that reported it and presumably many more that didn't.

We use Firebase 11.6.0 and Unity 2022.3.20. One of the reporters has Galaxy S23+ and wrote that the issue is reproduced 100% of the time. Reinstalling and device restarting didn't help.

**Comment by BrooklynDipi** [comment]
> Hello there, we experience this one as well. We have several users that reported it and presumably many more that didn't.
> 
> We use Firebase 11.6.0 and Unity 2022.3.20. One of the reporters has Galaxy S23+ and wrote that the issue is reproduced 100% of the time. Reinstalling and device restarting didn't help.

I have the 23 Ultra and I was getting it randomly so that's very odd. Very frustrating. We were running ads on our app and getting many comments complaining about the same issue. 

Ultimately, our backend dev created his own solution for me to use. Hopefully this gets fixed tho as I'd love to use it for other features.  Don't have much help otherwise but you are seen!

**Comment by georgemarkosian** [comment]
> > Hello there, we experience this one as well. We have several users that reported it and presumably many more that didn't.
> > We use Firebase 11.6.0 and Unity 2022.3.20. One of the reporters has Galaxy S23+ and wrote that the issue is reproduced 100% of the time. Reinstalling and device restarting didn't help.
> 
> I have the 23 Ultra and I was getting it randomly so that's very odd. Very frustrating. We were running ads on our app and getting many comments complaining about the same issue.
> 
> Ultimately, our backend dev created his own solution for me to use. Hopefully this gets fixed tho as I'd love to use it for other features. Don't have much help otherwise but you are seen!

Thank you for your response. Our app relies on the remote config at the very start so the issue is critical. While only a fraction of our users are affected, some of them are subscribers who could unsubscribe and leave.

We'll try to find a workaround but we hope this will be addressed soon.

**Comment by tallior** [comment]
Any updates or workarounds for this issue ?

**Comment by a-maurice** [comment]
My understanding of the underlying issue is that when the dependencies are being linked dynamically, there is a danger that it is getting two separate versions of Firebase/Core, and then using them for different calls, which causes the issue (as described here: https://github.com/firebase/quickstart-unity/issues/1198#issuecomment-1040690857)

The workaround that we've recommended is to use static linking, but that seems to not be possible with some other SDKs, like the Facebook one.  Unfortunately there isn't a ton we can do at our level, as it seems to mostly be an issue with how Cocoapods is linking in the different libraries.

Some things that you can try to do, using the Swift Package Manager instead of Cocoapods.  We haven't done it ourselves, but theoretically you could get the Firebase (and/or Facebook) frameworks through SPM, which might help.  From some searching, there are also some Cocoapod plugins that allow you to specify different linking patterns per pod, such as https://github.com/microsoft/cocoapods-pod-linkage, which could help.

**Comment by tallior** [comment]
Thanks for the reply @a-maurice 
I will give that a look, but i am not sure how this solution would work in the context of a Unity game (and not a standard, native iOS app).

Is there any way to remove the usage of pods altogether (for Firebase / Facebook) and include it directly in our project somehow?

**Comment by abhishekbodhekar** [comment]
any update on this?

**Comment by xandudex** [comment]
It still happening. All the suggestions are to disable "Link Frameworks Statically", but it breaks facebook sdk, and it's not a fix for a lot of devs

**Comment by xandudex** [comment]
Think I've fixed in my case.I have replaced:

_Preparation_
`var remoteConfig = FirebaseRemoteConfig.GetInstance(FirebaseApp.DefaultInstance);`

That:
`await remoteConfig.FetchAsync();`
`var activateResult = await remoteConfig.ActivateAsync();`

With:
`var activateResult = await remoteConfig.FetchAndActivateAsync();`

Sounds stupid but looks like FetchAndActivateAsync does something more then old approach.

**Comment by BrooklynDipi** [comment]
> Think I've fixed in my case.I have replaced:
> 
> _Preparation_ `var remoteConfig = FirebaseRemoteConfig.GetInstance(FirebaseApp.DefaultInstance);`
> 
> That: `await remoteConfig.FetchAsync();` `var activateResult = await remoteConfig.ActivateAsync();`
> 
> With: `var activateResult = await remoteConfig.FetchAndActivateAsync();`
> 
> Sounds stupid but looks like FetchAndActivateAsync does something more then old approach.

Hm. I'm glad this worked for you. I believe I tried this in my testing and still experienced issues. Maybe it was the preparation part of your code that is the fix? I am leaning towards that maybe being the real solution here. 

Also, I have attempted to let the Facebook SDK for Unity dev team know about this issue via a connect I had recently. Have heard nothing back. Probably never will with the state of Meta right now.

**Comment by xandudex** [comment]
More researched. No matter is there facebook sdk or not, dynamic linkage or static, minimal pods I've used: 
`  pod 'Firebase/Core', '11.9.0'
  pod 'Firebase/Crashlytics', '11.9.0'
  pod 'Firebase/Firestore', '11.9.0'
  pod 'Firebase/RemoteConfig', '11.9.0'
  pod 'FirebaseInstallations'
  pod 'Google-Mobile-Ads-SDK', '~> 11.13.0'
  pod 'GoogleUserMessagingPlatform', '2.7.0'`

the problem still exist. I'm assuming that internaly we are not getting fetch status LAST_FETCH_STATUS_THROTTLED  for too many attempts to fetch.

**Comment by nisako** [comment]
Any update on this? It's crazy to see one of main features of firebase not working reliable on one of the major platform.

**Comment by xandudex** [comment]
The solution wasn't found. For now we are just caching a successful fetch and use it as default on the next load. In the future we will try other platforms.

**Comment by a-maurice** [comment]
Hey all,

Sorry there hasn't been much movement on this, since the issue is with how Cocoapods links in the libraries, and that is being phased out in favor of Swift Package Manager, there unfortunately isn't really a workaround or quick fix we can offer on the Firebase Unity side of things. We will be migrating off of Cocoapods to Swift Package Manager ourselves, which requires changes to the External Dependency Manager to handle it, but in the meantime the primary workaround would be modifying the XCode project that Unity generates to link against the Firebase iOS dependencies a different way, as described here: https://firebase.google.com/docs/ios/installation-methods

**Comment by burakomer** [comment]
Hey everyone,

I have worked on a workaround for adding dependencies from Swift Package Manager instead of Cocoapods. So far my tests have been good, no hangs on Remote Config. Also right now I am consistently seeing Analytics events as before they seemed to be broken sometimes, just like this Remote Config bug. I hope this helps people in need until there's an official fix.

**FirebaseSpmPostProcess.cs**
```
#if UNITY_IOS
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.iOS.Xcode;
using Debug = UnityEngine.Debug;

/// <summary>
/// A workaround for integrating Firebase iOS SDK via Swift Package Manager (SPM) in Unity iOS builds.
/// To remove pods, you need to edit the Dependencies.xml files in Firebase Editor folder and remove the iosPod entries.
/// Note the Firebase iOS version inside Dependencies.xml to use in <see cref="FirebaseSwiftPackageVersion"/>
/// Edit <see cref="FirebasePackages"/> to your requirements.
/// </summary>
internal class FirebaseSpmPostprocess : IPostprocessBuildWithReport
{
    private const string LoggerName = nameof(FirebaseSpmPostprocess);

    public int callbackOrder => int.MaxValue;

    private const string FirebaseSwiftPackageUrl = "https://github.com/firebase/firebase-ios-sdk.git";
    private const string FirebaseSwiftPackageVersion = "11.14.0";

    private static readonly string[] FirebasePods =
    {
        "pod 'Firebase", "pod \"Firebase",
        "pod 'GoogleUtilities", "pod \"GoogleUtilities",
        "pod 'GTMSessionFetcher", "pod \"GTMSessionFetcher",
        "pod 'gRPC", "pod \"gRPC",
        "pod 'nanopb", "pod \"nanopb"
    };

    private static readonly string[] FirebasePackages =
    {
        "FirebaseCore",
        "FirebaseAnalytics",
        "FirebaseCrashlytics",
        "FirebaseRemoteConfig",
        "FirebaseInstallations",
    };

    public void OnPostprocessBuild(BuildReport report)
    {
        if (report.summary.platform != BuildTarget.iOS) return;

        var buildPath = report.summary.outputPath;
        var pbxPath = PBXProject.GetPBXProjectPath(buildPath);

        AddFirebaseSwiftPackage(pbxPath);
        RemoveOldCrashlyticsRunScript(pbxPath);
        AddNewCrashlyticsRunScript(pbxPath);
    }

    private static void AddFirebaseSwiftPackage(string pbxPath)
    {
        var pbx = new PBXProject();
        pbx.ReadFromFile(pbxPath);

        var packageGuid = pbx.AddRemotePackageReferenceAtVersion(
            FirebaseSwiftPackageUrl,
            FirebaseSwiftPackageVersion);

        // Only the UnityFramework target is needed for Firebase
        var targets = new[]
        {
            // pbx.GetUnityMainTargetGuid(),
            pbx.GetUnityFrameworkTargetGuid(),
        };

        foreach (var t in targets)
        foreach (var product in FirebasePackages)
            pbx.AddRemotePackageFrameworkToProject(t, product, packageGuid, false);

        pbx.WriteToFile(pbxPath);

        Debug.Log($"[{LoggerName}] Added Firebase Swift Package to {pbxPath}");
    }

    private static void RemoveOldCrashlyticsRunScript(string pbxPath)
    {
        var pbx = new PBXProject();
        pbx.ReadFromFile(pbxPath);

        string phaseGuid = null;

        var targets = new[]
        {
            pbx.GetUnityMainTargetGuid(),
            pbx.GetUnityFrameworkTargetGuid(),
        };

        for (var i = 0; i < targets.Length; i++)
        {
            var target = targets[i];
            var guids = pbx.GetAllBuildPhasesForTarget(target);
            foreach (var guid in guids)
            {
                var buildPhaseName = pbx.GetBuildPhaseName(guid);
                if (string.IsNullOrEmpty(buildPhaseName)) continue;
                if (!buildPhaseName.Contains("Crashlytics"))
                    continue;
                phaseGuid = guid;
                break;
            }

            if (phaseGuid != null)
            {
                PBXProjectTextManipulator.RemoveBuildPhaseByGuid(pbxPath, phaseGuid);

                Debug.Log($"[{LoggerName}] Removed old Crashlytics Run Script from target {i} in {pbxPath}");
            }
            else
            {
                Debug.LogWarning($"[{LoggerName}] No old Crashlytics Run Script found in target {i} in {pbxPath}");
            }
        }
    }

    private static void AddNewCrashlyticsRunScript(string pbxPath)
    {
        var pbx = new PBXProject();
        pbx.ReadFromFile(pbxPath);

        const string shell = @"/bin/sh -x";

        const string script = @"CRASHLYTICS_DIR=""${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics""
RUN_SCRIPT=""${CRASHLYTICS_DIR}/run""
UPLOAD_BIN=""${CRASHLYTICS_DIR}/upload-symbols""

chmod +x ""$RUN_SCRIPT"" ""$UPLOAD_BIN""

""$RUN_SCRIPT"" -gsp ""${PROJECT_DIR}/GoogleService-Info.plist"" \
              -dSYM ""${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}""
";

        List<string> inputPaths = new()
        {
            "$(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist",
            "$(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)",
            "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}",
            "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist",
            "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}",
        };

        var targets = new[]
        {
            pbx.GetUnityMainTargetGuid(),
            pbx.GetUnityFrameworkTargetGuid(),
        };

        foreach (var targetGuid in targets)
        {
            pbx.AddShellScriptBuildPhase(targetGuid, "Crashlytics Run Script", shell, script, inputPaths);
        }

        Debug.Log($"[{LoggerName}] Added new Crashlytics Run Script to {pbxPath}");

        pbx.WriteToFile(pbxPath);
    }
}
#endif
```

**PBXProjectTextManipulator.cs**
```
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEngine;

public static class PBXProjectTextManipulator
{
    /// <summary>
    /// Removes a build phase by its GUID from the project.pbxproj file
    /// </summary>
    /// <param name="projectPath">Path to the project.pbxproj file</param>
    /// <param name="buildPhaseGuid">The GUID of the build phase to remove (e.g., "D4FF4432A26686ABF4D7C48F")</param>
    /// <returns>True if the build phase was found and removed, false otherwise</returns>
    public static bool RemoveBuildPhaseByGuid(string projectPath, string buildPhaseGuid)
    {
        if (!File.Exists(projectPath))
        {
            Debug.LogError($"Project file not found: {projectPath}");
            return false;
        }

        var content = File.ReadAllText(projectPath);
        var originalContent = content;
        var removed = false;

        content = RemoveBuildPhaseObject(content, buildPhaseGuid);
        
        content = RemoveBuildPhaseReferences(content, buildPhaseGuid);

        removed = content != originalContent;

        if (removed)
        {
            File.WriteAllText(projectPath, content);
            Debug.Log($"Successfully removed build phase {buildPhaseGuid}");
        }
        else
        {
            Debug.LogWarning($"Build phase {buildPhaseGuid} not found in project");
        }

        return removed;
    }

    /// <summary>
    /// Removes a build phase object definition from the project content
    /// </summary>
    private static string RemoveBuildPhaseObject(string content, string buildPhaseGuid)
    {
        // Pattern to match the entire build phase object definition
        // Example:
        // D4FF4432A26686ABF4D7C48F /* Crashlytics Run Script */ = {
        //     isa = PBXShellScriptBuildPhase;
        //     buildActionMask = 2147483647;
        //     files = (
        //     );
        //     inputPaths = (
        //         "$(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist",
        //         ...
        //     );
        //     name = "Crashlytics Run Script";
        //     outputPaths = (
        //     );
        //     runOnlyForDeploymentPostprocessing = 0;
        //     shellPath = "/bin/sh -x";
        //     shellScript = "...";
        // };

        return RemoveBuildPhaseObjectAdvanced(content, buildPhaseGuid);
    }

    /// <summary>
    /// Advanced build phase object removal that properly handles nested braces
    /// </summary>
    private static string RemoveBuildPhaseObjectAdvanced(string content, string buildPhaseGuid)
    {
        // Find the start of the build phase definition
        var startPattern = $@"{Regex.Escape(buildPhaseGuid)}\s*/\*[^*]*\*/\s*=\s*\{{";
        var startMatch = Regex.Match(content, startPattern);
        
        if (!startMatch.Success)
            return content;

        var startIndex = startMatch.Index;
        var braceCount = 0;
        var currentIndex = startMatch.Index + startMatch.Length - 1; // Position at the opening brace
        var inString = false;
        var stringChar = '\0';

        // Parse through the content to find the matching closing brace
        while (currentIndex < content.Length)
        {
            var c = content[currentIndex];

            if (!inString)
            {
                if (c == '"' || c == '\'')
                {
                    inString = true;
                    stringChar = c;
                }
                else if (c == '{')
                {
                    braceCount++;
                }
                else if (c == '}')
                {
                    braceCount--;
                    if (braceCount == 0)
                    {
                        var endIndex = currentIndex + 1;
                        while (endIndex < content.Length && char.IsWhiteSpace(content[endIndex]))
                            endIndex++;
                        
                        if (endIndex < content.Length && content[endIndex] == ';')
                            endIndex++;

                        var beforeBuildPhase = content.Substring(0, startIndex);
                        var afterBuildPhase = content.Substring(endIndex);
                        
                        beforeBuildPhase = beforeBuildPhase.TrimEnd();
                        if (afterBuildPhase.StartsWith("\n"))
                            afterBuildPhase = afterBuildPhase.Substring(1);

                        return beforeBuildPhase + "\n" + afterBuildPhase;
                    }
                }
            }
            else
            {
                if (c == stringChar && (currentIndex == 0 || content[currentIndex - 1] != '\\'))
                {
                    inString = false;
                }
            }

            currentIndex++;
        }

        return content; // No matching brace found, return original
    }

    /// <summary>
    /// Removes build phase references from target buildPhases arrays
    /// </summary>
    private static string RemoveBuildPhaseReferences(string content, string buildPhaseGuid)
    {
        // Pattern to match buildPhases arrays and remove the specific GUID
        // Example:
        // buildPhases = (
        //     EA63A9D7866BE67E90427C30 /* [CP] Check Pods Manifest.lock */,
        //     9D25AB9A213FB47800354C27 /* Headers */,
        //     D4FF4432A26686ABF4D7C48F /* Crashlytics Run Script */,
        //     9D25AB9B213FB47800354C27 /* Resources */,
        // );

        // Find all buildPhases arrays
        var buildPhasesPattern = @"buildPhases\s*=\s*\(\s*((?:[^)]+(?:\([^)]*\)[^)]*)*)*)\s*\);";
        
        return Regex.Replace(content, buildPhasesPattern, match =>
        {
            var buildPhasesContent = match.Groups[1].Value;
            
            // Remove the specific build phase GUID from this array
            var updatedBuildPhases = RemoveGuidFromArray(buildPhasesContent, buildPhaseGuid);
            
            return $"buildPhases = (\n{updatedBuildPhases}\n\t\t);";
        }, RegexOptions.Multiline | RegexOptions.Singleline);
    }

    /// <summary>
    /// Removes a specific GUID from a buildPhases array content
    /// </summary>
    private static string RemoveGuidFromArray(string arrayContent, string guidToRemove)
    {
        var lines = arrayContent.Split('\n')
            .Select(line => line.Trim())
            .Where(line => !string.IsNullOrEmpty(line))
            .ToList();

        var filteredLines = new List<string>();

        foreach (var line in lines)
        {
            if (!line.Contains(guidToRemove))
            {
                filteredLines.Add(line);
            }
        }

        if (filteredLines.Count == 0)
            return "";

        return string.Join("\n", filteredLines.Select((line, index) => 
        {
            var formattedLine = $"\t\t\t{line}";
            
            if (index == filteredLines.Count - 1)
            {
                formattedLine = formattedLine.TrimEnd(',', ' ', '\t');
            }
            else
            {
                if (!formattedLine.TrimEnd().EndsWith(","))
                    formattedLine += ",";
            }
            
            return formattedLine;
        }));
    }
}
```

**Comment by niccolo-hare** [comment]
Hi there, I'll be closing this issue since it's aging. But if you're still encountering similar issue(s) feel free to reopen this, and do react with a _thumbs up_ emote on the author's original post. This will help give us a better idea of its severity while we investigate the issue. Thanks!
